"""empty message

Revision ID: 82af49d983c7
Revises: 4468767c6d24
Create Date: 2017-10-11 18:18:15.968078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82af49d983c7'
down_revision = '4468767c6d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglistsitems', sa.Column('shoppinglistid', sa.Integer(), nullable=True))
    op.drop_constraint(u'shoppinglistsitems_shoppinglistname_fkey', 'shoppinglistsitems', type_='foreignkey')
    op.create_foreign_key(None, 'shoppinglistsitems', 'shoppinglists', ['shoppinglistid'], ['id'])
    op.drop_column('shoppinglistsitems', 'shoppinglistname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglistsitems', sa.Column('shoppinglistname', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shoppinglistsitems', type_='foreignkey')
    op.create_foreign_key(u'shoppinglistsitems_shoppinglistname_fkey', 'shoppinglistsitems', 'shoppinglists', ['shoppinglistname'], ['id'])
    op.drop_column('shoppinglistsitems', 'shoppinglistid')
    # ### end Alembic commands ###
