"""empty message

Revision ID: b3489eaebccb
Revises: a16c24caba28
Create Date: 2017-10-05 14:19:55.924453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3489eaebccb'
down_revision = 'a16c24caba28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
